tempdir= 'C:\Users\jmara\OneDrive\Desktop\Rat video series\temp training';

options = trainingOptions('sgdm', ...
        'MiniBatchSize',16, ....
        'InitialLearnRate',1e-3, ...
        'MaxEpochs',20, ... 
        'CheckpointPath',tempdir, ...
        'ValidationData',processedValData);

[detector,info] = trainYOLOv2ObjectDetector(processedTrainData,lgraph,options);